// <auto-generated />
using System;
using LogMind.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogMind.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogMindDbContext))]
    [Migration("20260613030000_AddIncidents")]
    partial class AddIncidents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LogMind.Core.Models.AiExplanationCache", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("EmbeddingVector").HasColumnType("TEXT");
                    b.Property<string>("ExplanationJson").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("HitCount").HasColumnType("INTEGER");
                    b.Property<bool>("IsInvalidated").HasColumnType("INTEGER");
                    b.Property<DateTime>("LastUsedAt").HasColumnType("TEXT");
                    b.Property<string>("Level").IsRequired().HasColumnType("TEXT");
                    b.Property<int?>("LogEntryId").HasColumnType("INTEGER");
                    b.Property<string>("MessageHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Model").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("NormalizedMessage").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PromptVersion").IsRequired().HasColumnType("TEXT");
                    b.Property<int?>("RelatedIssueId").HasColumnType("INTEGER");
                    b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("LogEntryId");
                    b.HasIndex("MessageHash").IsUnique().HasDatabaseName("ix_cache_hash");
                    b.HasIndex("RelatedIssueId");
                    b.HasIndex("IsInvalidated", "LastUsedAt").HasDatabaseName("ix_cache_invalidated_lastused");
                    b.HasIndex("Source", "CreatedAt").HasDatabaseName("ix_cache_source_createdat");
                    b.ToTable("AiExplanationCache");
                });

            modelBuilder.Entity("LogMind.Core.Models.Alert", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime?>("AcknowledgedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsAcknowledged").HasColumnType("INTEGER");
                    b.Property<int>("OccurrenceCount").HasColumnType("INTEGER");
                    b.Property<string>("Pattern").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RuleName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SampleMessage").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ThresholdCount").HasColumnType("INTEGER");
                    b.Property<DateTime>("TriggeredAt").HasColumnType("TEXT");
                    b.Property<int>("WindowMinutes").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("IsAcknowledged");
                    b.HasIndex("Source");
                    b.HasIndex("TriggeredAt");
                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("LogMind.Core.Models.ErrorPattern", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasColumnType("INTEGER");
                    b.Property<int?>("KnownIssueId").HasColumnType("INTEGER");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Pattern").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PatternType").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Severity").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Source").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("KnownIssueId");
                    b.ToTable("ErrorPatterns");
                });

            modelBuilder.Entity("LogMind.Core.Models.Incident", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("EventCount").HasDefaultValue(1).HasColumnType("INTEGER");
                    b.Property<DateTime>("FirstSeenAt").HasColumnType("TEXT");
                    b.Property<string>("IncidentFingerprint").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("LastSeenAt").HasColumnType("TEXT");
                    b.Property<DateTime?>("ResolvedAt").HasColumnType("TEXT");
                    b.Property<string>("RootCauseSummary").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("RootLogMessage").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Severity").IsRequired().HasDefaultValue("High").HasColumnType("TEXT");
                    b.Property<string>("SourceSystem").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasDefaultValue("Open").HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("IncidentFingerprint").HasDatabaseName("ix_incident_fingerprint");
                    b.HasIndex("Status").HasDatabaseName("ix_incident_status");
                    b.HasIndex("SourceSystem", "LastSeenAt").HasDatabaseName("ix_incident_source_lastseen");
                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("LogMind.Core.Models.IncidentEvent", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("CorrelationBasis").IsRequired().HasColumnType("TEXT");
                    b.Property<float>("CorrelationScore").HasDefaultValue(0f).HasColumnType("REAL");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("IncidentId").HasColumnType("INTEGER");
                    b.Property<int>("LogEntryId").HasColumnType("INTEGER");
                    b.Property<int>("MinutesFromRoot").HasDefaultValue(0).HasColumnType("INTEGER");
                    b.Property<string>("Role").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Sequence").HasDefaultValue(0).HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("LogEntryId").HasDatabaseName("ix_incident_event_logentry");
                    b.HasIndex("IncidentId", "Sequence").HasDatabaseName("ix_incident_event_sequence");
                    b.ToTable("IncidentEvents");
                });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssue", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ErrorPattern").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime?>("LastOccurredAt").HasColumnType("TEXT");
                    b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("KnownIssues");
                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified), Description = "SAP RFC connection times out or is refused due to misconfigured gateway", ErrorPattern = "RFC_ERROR|CONNECT_FAILURE|SAPException", Source = "SAP", Title = "SAP RFC Connection Failure", UpdatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified) },
                        new { Id = 2, CreatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified), Description = "Odoo API connection times out during SAP-Odoo synchronization", ErrorPattern = "ConnectionTimeout|timeout|ETIMEDOUT|Connection refused|ConnectError", Source = "SapOdoo", Title = "SapOdoo API Connection Timeout", UpdatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified) },
                        new { Id = 3, CreatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified), Description = "Data mapping error during SAP to Odoo sync, typically caused by missing or mismatched field mappings", ErrorPattern = "mapping.*error|IDOC|SyncException|sync_error|KeyError|field.*not found", Source = "SapOdoo", Title = "SapOdoo Sync Mapping Error", UpdatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified) });
                });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssueEmbedding", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("GeneratedAt").HasColumnType("TEXT");
                    b.Property<int>("KnownIssueId").HasColumnType("INTEGER");
                    b.Property<string>("VectorJson").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("KnownIssueId");
                    b.ToTable("KnownIssueEmbeddings");
                });

            modelBuilder.Entity("LogMind.Core.Models.LogEntry", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ErrorCode").HasColumnType("TEXT");
                    b.Property<DateTime>("IngestedAt").HasColumnType("TEXT");
                    b.Property<string>("Level").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("LogFile").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Message").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("StackTrace").HasColumnType("TEXT");
                    b.Property<DateTime>("Timestamp").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Level");
                    b.HasIndex("Source");
                    b.HasIndex("Timestamp");
                    b.HasIndex("Source", "Level").HasDatabaseName("ix_logs_source_level");
                    b.HasIndex("Timestamp", "Id").HasDatabaseName("ix_logs_timestamp_id");
                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("LogMind.Core.Models.OperationalDependency", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Criticality").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("DependencyType").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ImpactWeight").HasDefaultValue(0).HasColumnType("INTEGER");
                    b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("INTEGER");
                    b.Property<string>("SourceSystem").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("TargetSystem").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("SourceSystem").HasDatabaseName("ix_opdep_source");
                    b.HasIndex("IsActive").HasDatabaseName("ix_opdep_active");
                    b.ToTable("OperationalDependencies");
                });

            modelBuilder.Entity("LogMind.Core.Models.OperationalKnowledge", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("ApplicableSources").IsRequired().HasDefaultValue("[]").HasColumnType("TEXT");
                    b.Property<string>("Category").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Content").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("EmbeddingVector").HasColumnType("TEXT");
                    b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("INTEGER");
                    b.Property<string>("System").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Tags").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("IsActive").HasDatabaseName("ix_opknowledge_active");
                    b.HasIndex("Category").HasDatabaseName("ix_opknowledge_category");
                    b.ToTable("OperationalKnowledge");
                });

            modelBuilder.Entity("LogMind.Core.Models.Solution", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("KnownIssueId").HasColumnType("INTEGER");
                    b.Property<bool>("NeedsReview").HasColumnType("INTEGER");
                    b.Property<string>("References").HasColumnType("TEXT");
                    b.Property<string>("Steps").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("Upvotes").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("KnownIssueId");
                    b.ToTable("Solutions");
                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified), KnownIssueId = 1, NeedsReview = false, References = "SAP Note 1234567", Steps = "1. Open SAP Management Console\n2. Navigate to SAP Gateway\n3. Stop and restart the gateway service\n4. Monitor connection logs for reconnection", Title = "Restart SAP Gateway Service", Upvotes = 12 },
                        new { Id = 2, CreatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified), KnownIssueId = 2, NeedsReview = false, References = "Odoo Admin Guide — Timeouts", Steps = "1. Check Odoo server is running and reachable\n2. Increase xmlrpc timeout in SapOdoo config\n3. Check firewall rules between SAP and Odoo servers\n4. Verify Odoo URL and credentials in appsettings", Title = "Check Odoo Server and Increase Timeout", Upvotes = 6 },
                        new { Id = 3, CreatedAt = new DateTime(2024,1,1,0,0,0,0,DateTimeKind.Unspecified), KnownIssueId = 3, NeedsReview = false, References = "SapOdoo Field Mapping Runbook", Steps = "1. Review the field mapping config in SapOdoo settings\n2. Compare SAP IDOC structure against Odoo model fields\n3. Add any missing field mappings and redeploy\n4. Re-run the failed sync batch from the SapOdoo admin panel", Title = "Fix SapOdoo Field Mapping Config", Upvotes = 4 });
                });

            modelBuilder.Entity("LogMind.Core.Models.SolutionFeedback", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int?>("LogEntryId").HasColumnType("INTEGER");
                    b.Property<string>("Note").HasColumnType("TEXT");
                    b.Property<int>("SolutionId").HasColumnType("INTEGER");
                    b.Property<bool>("Worked").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("LogEntryId").HasDatabaseName("ix_feedback_logentryid");
                    b.HasIndex("SolutionId").HasDatabaseName("ix_feedback_solutionid");
                    b.ToTable("SolutionFeedback");
                });

            modelBuilder.Entity("LogMind.Core.Models.AiExplanationCache", b =>
                {
                    b.HasOne("LogMind.Core.Models.LogEntry", "LogEntry").WithMany().HasForeignKey("LogEntryId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("LogMind.Core.Models.KnownIssue", "RelatedIssue").WithMany().HasForeignKey("RelatedIssueId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("LogEntry");
                    b.Navigation("RelatedIssue");
                });

            modelBuilder.Entity("LogMind.Core.Models.ErrorPattern", b =>
                {
                    b.HasOne("LogMind.Core.Models.KnownIssue", "KnownIssue").WithMany().HasForeignKey("KnownIssueId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("KnownIssue");
                });

            modelBuilder.Entity("LogMind.Core.Models.Incident", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("LogMind.Core.Models.IncidentEvent", b =>
                {
                    b.HasOne("LogMind.Core.Models.Incident", "Incident").WithMany("Events").HasForeignKey("IncidentId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("LogMind.Core.Models.LogEntry", "LogEntry").WithMany().HasForeignKey("LogEntryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Incident");
                    b.Navigation("LogEntry");
                });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssueEmbedding", b =>
                {
                    b.HasOne("LogMind.Core.Models.KnownIssue", "KnownIssue").WithMany().HasForeignKey("KnownIssueId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("KnownIssue");
                });

            modelBuilder.Entity("LogMind.Core.Models.Solution", b =>
                {
                    b.HasOne("LogMind.Core.Models.KnownIssue", "KnownIssue").WithMany("Solutions").HasForeignKey("KnownIssueId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("KnownIssue");
                });

            modelBuilder.Entity("LogMind.Core.Models.SolutionFeedback", b =>
                {
                    b.HasOne("LogMind.Core.Models.LogEntry", "LogEntry").WithMany().HasForeignKey("LogEntryId").OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("LogMind.Core.Models.Solution", "Solution").WithMany("Feedback").HasForeignKey("SolutionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("LogEntry");
                    b.Navigation("Solution");
                });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssue", b => { b.Navigation("Solutions"); });
            modelBuilder.Entity("LogMind.Core.Models.Solution", b => { b.Navigation("Feedback"); });
#pragma warning restore 612, 618
        }
    }
}
