// <auto-generated />
using System;
using LogMind.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogMind.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogMindDbContext))]
    partial class LogMindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LogMind.Core.Models.Alert", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime?>("AcknowledgedAt").HasColumnType("TEXT");
                b.Property<bool>("IsAcknowledged").HasColumnType("INTEGER");
                b.Property<int>("OccurrenceCount").HasColumnType("INTEGER");
                b.Property<string>("Pattern").IsRequired().HasColumnType("TEXT");
                b.Property<string>("RuleName").IsRequired().HasColumnType("TEXT");
                b.Property<string>("SampleMessage").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                b.Property<int>("ThresholdCount").HasColumnType("INTEGER");
                b.Property<DateTime>("TriggeredAt").HasColumnType("TEXT");
                b.Property<int>("WindowMinutes").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("IsAcknowledged");
                b.HasIndex("Source");
                b.HasIndex("TriggeredAt");
                b.ToTable("Alerts");
            });

            modelBuilder.Entity("LogMind.Core.Models.ErrorPattern", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<int?>("KnownIssueId").HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Pattern").IsRequired().HasColumnType("TEXT");
                b.Property<string>("PatternType").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Severity").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Source").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("KnownIssueId");
                b.ToTable("ErrorPatterns");
            });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssue", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<string>("Description").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ErrorPattern").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("KnownIssues");
            });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssueEmbedding", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("GeneratedAt").HasColumnType("TEXT");
                b.Property<int>("KnownIssueId").HasColumnType("INTEGER");
                b.Property<string>("VectorJson").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("KnownIssueId");
                b.ToTable("KnownIssueEmbeddings");
            });

            modelBuilder.Entity("LogMind.Core.Models.LogEntry", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("ErrorCode").HasColumnType("TEXT");
                b.Property<DateTime>("IngestedAt").HasColumnType("TEXT");
                b.Property<string>("Level").IsRequired().HasColumnType("TEXT");
                b.Property<string>("LogFile").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Message").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Source").IsRequired().HasColumnType("TEXT");
                b.Property<string>("StackTrace").HasColumnType("TEXT");
                b.Property<DateTime>("Timestamp").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Level");
                b.HasIndex("Source");
                b.HasIndex("Timestamp");
                b.ToTable("LogEntries");
            });

            modelBuilder.Entity("LogMind.Core.Models.Solution", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<int>("KnownIssueId").HasColumnType("INTEGER");
                b.Property<string>("References").HasColumnType("TEXT");
                b.Property<string>("Steps").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Title").IsRequired().HasColumnType("TEXT");
                b.Property<int>("Upvotes").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("KnownIssueId");
                b.ToTable("Solutions");
            });

            modelBuilder.Entity("LogMind.Core.Models.ErrorPattern", b =>
            {
                b.HasOne("LogMind.Core.Models.KnownIssue", "KnownIssue")
                    .WithMany()
                    .HasForeignKey("KnownIssueId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("KnownIssue");
            });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssueEmbedding", b =>
            {
                b.HasOne("LogMind.Core.Models.KnownIssue", "KnownIssue")
                    .WithMany()
                    .HasForeignKey("KnownIssueId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("KnownIssue");
            });

            modelBuilder.Entity("LogMind.Core.Models.Solution", b =>
            {
                b.HasOne("LogMind.Core.Models.KnownIssue", "KnownIssue")
                    .WithMany("Solutions")
                    .HasForeignKey("KnownIssueId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("KnownIssue");
            });

            modelBuilder.Entity("LogMind.Core.Models.KnownIssue", b =>
            {
                b.Navigation("Solutions");
            });
#pragma warning restore 612, 618
        }
    }
}
